#!/bin/bash -e

function changeFont() {
    if [ "$origfont" = true ] && [ -f "/data/data/com.termux/files/home/df_sandbox/fonts/termux-font.ttf" ]; then 
        mv -f /data/data/com.termux/files/home/df_sandbox/fonts/termux-font.ttf /data/data/com.termux/files/home/.termux/font.ttf
    elif [ -f "/data/data/com.termux/files/home/.termux/font.ttf" ]; then
        rm -f /data/data/com.termux/files/home/.termux/font.ttf
    fi
    termux-reload-settings
}

trap changeFont EXIT 
mkdir -p /data/data/com.termux/files/home/.termux/

origfont=false
if [[ -f "/data/data/com.termux/files/home/.termux/font.ttf" ]]; then
    mv -f /data/data/com.termux/files/home/.termux/font.ttf /data/data/com.termux/files/home/df_sandbox/fonts/termux-font.ttf
    origfont=true
fi

if [[ -f "/data/data/com.termux/files/home/df_sandbox/fonts/font.ttf" ]]; then
    cp /data/data/com.termux/files/home/df_sandbox/fonts/font.ttf /data/data/com.termux/files/home/.termux/font.ttf
    termux-reload-settings
fi

unset LD_PRELOAD
proot --link2symlink \
    -b /data:/data \
    -b /proc:/proc \
    -b /system:/system \
    -b /dev:/dev \
    -q qemu-x86_64 \
    -w / \
    -0 \
    -r /data/data/com.termux/files/home/df_sandbox/ \
    /bin/busybox env \
    TMPDIR=/tmp \
    HOME=/random \
    PREFIX=/usr \
    LANG=en_GB.UTF-8 \
    SHELL=/bin/bash \
    PATH=/bin/:/usr/bin/:/usr/sbin \
    TERM=xterm-256color \
    /dwarfs/df
